$(document).ready(function() {
  var LastWindSpeed;
  /**
   * Describe this function...
   */
  function updatecharts() {
    // Block#: 964
    com.fc.JavaScriptDistLib.Connio.connioReadData('_dev_821283688022652557',
      function(data) {
        // Block#: 966
        LastWindSpeed = (com.fc.JavaScriptDistLib.Connio.connionGetValue(data, 'mostRecent', 'windspeed'));
        // Block#: 970
        com.fc.JavaScriptDistLib.Label.setProperty["Text"]("lblWindSpeed", (String(LastWindSpeed) + String('m/s'))); // Block#: 974
        com.fc.JavaScriptDistLib.Gauge.setProperty["Current Value"]("GaugeWind", (com.fc.JavaScriptDistLib.MathLibrary.toNumber(LastWindSpeed)));
      },
      function(error_data) {
      });
  }
  // Block#: 977
  function on_btnGetDevices_click(e) {
    try {
      // Block#: 978
      updatecharts();
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="btnGetDevices"]').on('click', on_btnGetDevices_click);
  com.fc.JavaScriptDistLib.Connio.configure('{"api":{"url":"https://api.connio.com","app":"_app_796713082971687907","key":"_key_796713086353217836","secret":"2b05db40845242c09899346fca8da8ff"},"mqtt":{"host":"mqtt.connio.com","port":"8001","secure":true,"clientId":"_api_822826112907525233","username":"_key_822826112904411459","password":"cddd9bed10324fcea3ccef36e37924fa"}}');
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 949515-12607-254939-103344
